URL1: "http://www.goroyalclub.com:8015"
URL: "http://47.52.77.154:8015/Default/Login"
PASSWORD: a123
ADMIN: kaka
GS_NAME: GS_ly12
SCEO_LOGINNAME: sd_SCEO_ly12
SCEO_NAME: _SCEO_ly12
CEO_LOGINNAME: d_CEO_ly12
CEO_NAME: _CEO_ly12
league_LOGINNAME: ai_LEA_ly12
league_NAME: _LEA_ly12
HZ_LOGINNAME: Cly1
HZ_NAME: cly会长
ZD_NAME: ZD_ly12
DL_NAME: DL_ly12
HY_NAME: HY_ly12
PHONE: '180000000009'
PHONE1: '180000000008'