URL: "http://47.52.77.154:8015/Default/Login"
PASSWORD: a123
ADMIN: kaka
GS_NAME: ly0
SCEO_LOGINNAME: sdly1
SCEO_NAME: ly1
CEO_LOGINNAME: dcly2
CEO_NAME: ly2
league_LOGINNAME: aily3
league_NAME: ly3
HZ_LOGINNAME: cly4
HZ_NAME: ly4
ZD_NAME: ly5
DL_NAME: ly6
HY_NAME: ly7
PHONE: '8618062427380'