URL: "http://47.52.77.154:8015/Default/Login"
PASSWORD: a123
ADMIN: kaka
GS_NAME: GS_ly0
SCEO_LOGINNAME: sd_SCEO_ly1
SCEO_NAME: _SCEO_ly1
CEO_LOGINNAME: d_CEO_ly2
CEO_NAME: _CEO_ly2
league_LOGINNAME: ai_LEA_ly3
league_NAME: _LEA_ly3
HZ_LOGINNAME: cly4
HZ_NAME: ly4
ZD_NAME: ly5
DL_NAME: ly6
HY_NAME: ly7
PHONE: '8618062427380'