URL: "http://47.52.77.154:8015/Default/Login"
PASSWORD: a123
ADMIN: kaka
GS_NAME: ca0
SCEO_LOGINNAME: sda1
SCEO_NAME: a1
CEO_LOGINNAME: dca2
CEO_NAME: a2
league_NAME: ca3
HZ_LOGINNAME: ca4
HZ_NAME: a4
ZD_NAME: ca5
DL_NAME: ca6
HY_NAME: ca7
PHONE: '13333333311'