URL: "http://www.goroyalclub.com:8016"
URL1: "http://47.52.77.154:8015/Default/Login"
PASSWORD: a123
ADMIN: kaka
GS_NAME: GS_ly11
SCEO_LOGINNAME: sd_SCEO_ly11
SCEO_NAME: _SCEO_ly11
CEO_LOGINNAME: d_CEO_ly11
CEO_NAME: _CEO_ly11
league_LOGINNAME: ai_LEA_ly11
league_NAME: _LEA_ly11
HZ_LOGINNAME: Cly1
HZ_NAME: ly1
ZD_NAME: ZD_ly11
DL_NAME: DL_ly11
HY_NAME: HY_ly11
PHONE: '180000000009'
PHONE1: '180000000008'
HZ_ZSHY_original: 10000
ZD_original: 10000
ZD_ZSHY_original:
DL_original:
